---
title: Samuel Melden
timezone: UTC
collections:
  podcasts:
    title: Podcasts
    output: true
    permalink: "/acallfrom/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: |
  Sam is the Executive Director at The Center for Servant Leadership, a neighbor & co-organizer with Sylvania Avenue Neighbors, a parishioner at St. Andrew’s Episcopal Church and a proud and passionate citizen of Toledo, OH.
baseurl: ''
url: http://samuelmelden.com
permalink: pretty
markdown: kramdown
sass:
  style: :compressed
defaults:
  - scope:
    path: ""
    type: podcasts
  values:
    layout: podcast
    episode: ""
    soundcloudID: ""
prose:
  rooturl: _posts
  siteurl: http://samuelmelden.com
  media: img
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Title
        value: ''
    - name: published
      field:
        element: checkbox
        label: Published
        value: 'true'
